# KSQL configuration options
## ref: https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html
configurationOverrides:
    "ksql.logging.processing.topic.auto.create": true
    "ksql.logging.processing.stream.auto.create": true
    "ksql.service.id": radar_default_
    "ksql.persistence.default.format.key": AVRO
    "ksql.persistence.default.format.value": AVRO
    "ksql.sink.replicas": 3
    "ksql.streams.replication.factor": 3
    "ksql.internal.topic.replicas": 3
    "log4j.logger.processing": false
